FROM python:3.6

COPY "ta-lib-0.4.0-src.tar.gz" "/code/ta-lib-0.4.0-src.tar.gz"
COPY requirements.txt /code/requirements.txt

WORKDIR /code

RUN tar -zxvf ta-lib-0.4.0-src.tar.gz && \
    cd ta-lib && \
    ./configure --prefix=/usr && \
    make && \
    make install

WORKDIR /code

RUN pip install numpy && pip install -r requirements.txt

ADD . /code/


